# This is a basic workflow to help you get started with Actions

name: backend-develop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  deploy:
    #needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: haechang
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S su
            docker ps -a

            
            
  
